### ISSUE TITLE
Bugreport for Modrinth InfiniteCraft

### ISSUE THREAD

**Issue by Akentrus** [ProfessorQu/MCCraftingRecipes#1]
Hello, since there is no way of contacting you over Modrinth since you maybe have forgotten to add links for bugreports and since you said in the description to contact you i try my luck here. 

When playing singleplayer the combiner works fine but when installed on a server the console gives out an error and the GUI does not open (everything else works fine)

The error:

`[19:16:35] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@7e4e97df, suppressing error
java.lang.UnsupportedOperationException: Unable to construct this menu by type
at net.minecraft.class_1703.method_17358(class_1703.java:91) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_17355(class_3222.java:1056) ~[server-intermediary.jar:?]
at com.professorqu.block.custom.CombinerBlock.method_9534(CombinerBlock.java:43) ~[infinite-craft-1.3.3.jar:?]
at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1223) ~[server-intermediary.jar:?]
at net.minecraft.class_3225.method_14262(class_3225.java:348) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_12046(class_3244.java:1134) ~[server-intermediary.jar:?]
at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[server-intermediary.jar:?]
at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]`

I hope you are not inactive and it's possible to contact you here :) To make things easier my discord username is akentrus

I love your work and hope to be able to use it with friends! (The combiner) 

Have a great day!!!!

**Comment by ProfessorQu** [comment]
Hi! Wonderful! I did kind of leave the mod but I can certainly try to fix it! It's wild hearing that someone cares enough about my work thank you so much!! :smile:
I reached out to you on Discord so maybe we can fix this.
